### ISSUE TITLE
Bug report : Changing variable scope

### ISSUE THREAD

**Issue by avnerenv0** [env0/terraform-provider-env0#332]
> I had a variable set to a template scope, then changed it to global, and it didn't show up in the global variables section. I ran terraform taint on it and it showed up and worked as expected, but the modify by itself didn't do that for some reason.

**Comment by TomerHeber** [comment]
@yaronya @avnerenv0 

Could this be a backend issue (check GOOOOOOO):

Scope is organization in project variables:

![image](https://user-images.githubusercontent.com/12767692/163024354-2a685194-6d36-41a9-882c-f3c129e8b596.png)

But when I go to organization I don't see it in the UI:

![image](https://user-images.githubusercontent.com/12767692/163024613-3764d2f5-4224-47b3-b119-7834e8cc5232.png)

**Comment by GiliFaroEnv0** [comment]
> @yaronya @avnerenv0
> 
> Could this be a backend issue (check GOOOOOOO):
> 
> Scope is organization in project variables:
> 
> ![image](https://user-images.githubusercontent.com/12767692/163024354-2a685194-6d36-41a9-882c-f3c129e8b596.png)
> 
> But when I go to organization I don't see it in the UI:
> 
> ![image](https://user-images.githubusercontent.com/12767692/163024613-3764d2f5-4224-47b3-b119-7834e8cc5232.png)

@TomerHeber 
The **back-end doesn't support a change of scope**!
if we changed the scope it needs to delete and recreate,
I do think we need to validate this in the BE.
what happened here (in your screen shots) you just changed the scope but the scope-id didn't changed
that's why you see it in the template page (template-id) but not in the org page.

**Comment by yaronya** [comment]
I think the simplest solution would be to `ForceNew` on changes to scopes
