### ISSUE TITLE
 env0_environment resource and env0_configuration_variable `configuration` block

### ISSUE THREAD

**Issue by eranelbaz** [env0/terraform-provider-env0#347]
**Summary**:
Users reports that the `env0_environment` has an issue that reports that the `configuration` block is missing and tries to delete all `env0_configuration_variable` where environment scope is defined.

**Repro steps**:
1. define `env0_environment` resource
2. define `env0_configuration_variable` that uses `env0_environment` id
3. run tf refresh / apply on `env0_environment` 
4. expect to see no changes
5. actual behavior: env0 deletes `env0_configuration_variables`

** Potential workaround  **
lifecycle ignore_changes on configuration{}

** Let's try to understand why there is this issue and share your findings

**Comment by eranelbaz** [comment]
IMO we shouldn't let users define `env0_configuration_variable` and only let them define configuration variables on `env0_environment` scope

**Comment by TomerHeber** [comment]
@yaronya @eranelbaz 

I think this is what's happening:
1. when creating a new env0_configuration_variable in the scope of an environment - it creates the environment as expected.
2. Unfortunately, in the terraform layer/schema it does not update the internal configurations list in env_environment.
3. This causes confusion...  and refresh always tries to remove the configuration from env0_environment.
4. For some reason (for me at least) it doesn't remove the configuration. So it could be another issue.

I am wondering why configurations are a list in env0_environment...? why was it needed?
Regardless, at the moment I don't see an easy solution or non-breaking solution.

Let me know your thoughts.

**Comment by RLRabinowitz** [comment]
I think the issue described is wrong. As I understand it is as you have described @TomerHeber , the `configuration` block is what terraform tries to remove, in such a case

**Comment by yaronya** [comment]
@TomerHeber let's wait with a PR to remove this attribute.
What's planned is:
1. Merging your deprecation PR #360
2. We'll reach out to customers asking them about their usage and inform them on the planned change.
3. After there's green light - we'll open a PR to completely remove it and bump the provider with a minor version to `1.1.0`

I'll update when there's green light.

**Comment by ImIOImI** [comment]
As a customer, I have problems with the configuration object being a list. 
1) Currently, we can ignore the value of an env0_configuration_variable variable. This gives us the ability to update a value in the UI without TF trying to stomp the change later. Ignoring the values inside a list is fragile as it relies on the index of the variable and is easily broken by upstream changes... especially if we build the config block dynamically. 
1) I've observed providers not respecting the index values of lists (ie: IP firewall rules in azure) between runs and reporting non-sensical shifting of indexes as drift. While I have no evidence of Env0 doing this, I try to avoid those data types in general as it's not clear to me whether or not the issue is with Terraform's implementation or the providers'.

Ultimately, I'm not very smart. It would be much easier if the configuration block was a map. Imagine trying to unwind code like this in your head:

```
resource "env0_environment" "example" {
  for_each    = local.data
  name        = "${each.key}-${local.suffix}"
  project_id  = each.value["env0-project-id"]
  template_id = env0_template.template[each.key].id
  
  configuration = each.value["configuration-block"]

  lifecycle {
    ignore_changes = [
      configuration[2],
      configuration[5],
      configuration[10],
  }
}
```

Fortunately, most of the variables Env0 consumes in my stack are passed in via normal Terraform variables. If I was relying heavily on defined variables in the UI, this would not be a fun migration.

**Comment by yaronya** [comment]
> After there's green light - we'll open a PR to completely remove it and bump the provider with a minor version to 1.1.0

@TomerHeber we have a green light. Let's continue with remove the deprecated attribute and release a minor version afterwards 🙏

**Comment by yaronya** [comment]
Thanks @ImIOImI for the input.
Unfortunately, changing the configuration block from list to map would introduce a breaking change which we wouldn't want to introduce currently. We would, however, consider this as a candidate for a new major version (no ETA currently).

Moreover, managing environments both via UI and provider can cause these unwanted drifts (as this is the core behavior of TF) so I'd simply suggest to manage those solely via provider, if possible.

**Comment by TomerHeber** [comment]
The issue is blocked from now until a better solution is planned.
I have a closed PR that removes this field, but that is placed on hold for now.
