### ISSUE TITLE
Auto-associate team if it exists, if not, create it.

### ISSUE THREAD

**Issue by away168** [env0/terraform-provider-env0#632]
When using the TF Provider and with SAML integration, teams are automatically synced when a user logs in. 
When I create a new team in my Identity Provider workflow. (say a new team "Foo" is onboarding to env0).
env0 will automatically create the team "Foo" if a member of the team logs into env0.

However, through my automation process, I also want to automatically assign the Team "Foo" to certain projects with certain permissions.  My terraform code will create the group. However, sometimes, my terraform code will not get triggered before the user logs into env0.  (due to some syncing delays within our IdP workflow).  In this scenario, my TF code will fail because the Team already exists.

Would it be possible to have the Terraform provider do something like "adopt" a resource if it exists, rather than forcing me to import or delete the resource?

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/guardduty_organization_configuration

**Comment by roni-frantchi** [comment]
We looked into it - doing so clashes a bit with having a declarative IaC approach.  
There needs to be one source of truth - either SAML team sync is the source of truth, or the provider’s Terraform configuration.  

These kinds of “auto-import” or auto-reconcile aren’t typically supported by Terraform providers - if the object exists outside the IaC you need to be explicit about what you’re doing so you do not import something you did not intend to, and that is governed by another tool (in this instance, AD team sync).  

Sounds like however, we should allow splitting the responsibilities between SAML team sync and the provider:
- Terraform should control the team creation
- AD should control the team-user assignment

So maybe, what we should do is add a configuration to the SAML sync part, so that if on user log-in new teams will not be created.  
Users will only be assigned to teams if the teams already exist.  
That configuration will allow taking away the responsibility of team creation from SAML team sync, and only leave it with team-user-assignment.  

We'll track that handling the above on the env0 platform rather than our provider.
